version: 2

aliases:
  - &docker-image
    image: calband/circleci-calchart:1.2.0
  - &postgres-image
    image: circleci/postgres:9.6.2
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: circle_test
  - &cache-key
    v2-calchart-{{ arch }}-{{ checksum "package-lock.json" }}
  - &activate-venv
    run:
      name: Activate virtual environment
      command: echo 'export PATH="$HOME/project/venv/bin:$PATH"' >> $BASH_ENV

jobs:
  build-node:
      docker:
        - *docker-image
      steps:
        - checkout
        - restore_cache:
            key: *cache-key
        - run:
            name: Install Node requirements
            command: |
              npm --version
              npm install
        - save_cache:
            key: *cache-key
            paths:
              - node_modules
        - run:
            name: Build Javascript files
            command: npm run build
        - persist_to_workspace:
            root: "."
            paths:
              - calchart/static/
              - node_modules/
  build-python:
      docker:
        - *docker-image
      steps:
        - checkout
        - run:
            name: Create virtual environment
            command: python -m venv venv
        - *activate-venv
        - run:
            name: Install Python requirements
            command: |
              pip --version
              pip install -r requirements/dev.txt
        - persist_to_workspace:
            root: "."
            paths:
              - venv
  test-node:
      docker:
        - *docker-image
      steps:
        - checkout
        - attach_workspace:
            at: "."
        - run:
            name: Lint Javascript files
            command: npm run lint
        - run:
            name: Run Javascript unit tests
            command: npm test
  test-python:
      docker:
        - *docker-image
        - *postgres-image
      steps:
        - checkout
        - attach_workspace:
            at: "."
        - *activate-venv
        - run:
            name: Lint Python files
            command: flake8 calchart/
        - run:
            name: Wait for PostgreSQL
            command: sleep 10
        - run:
            name: Run Django tests
            command: python manage.py test --verbosity 3 --noinput
            working_directory: calchart
  test-cypress:
      docker:
        - *docker-image
        - *postgres-image
      steps:
        - checkout
        - attach_workspace:
            at: "."
        - *activate-venv
        - run:
            name: Wait for PostgreSQL
            command: sleep 10
        - run:
            name: Run cypress tests
            command: npm run cypress:run
        - store_artifacts:
            path: cypress/videos

workflows:
  version: 2

  calchart:
    jobs:
      - build-node
      - build-python
      - test-node:
          requires:
            - build-node
      - test-python:
          requires:
            - build-python
      - test-cypress:
          requires:
            - build-node
            - build-python
