version: 2

aliases:
  - &docker-image
    image: calband/circleci-calchart:1.2.3
  - &postgres-image
    image: circleci/postgres:9.6.2
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: circle_test
  - &cache-key
    v3-calchart-{{ arch }}-{{ checksum "yarn.lock" }}
  - &restore-cache
    restore_cache:
      key: *cache-key
  - &activate-venv
    run:
      name: Activate virtual environment
      command: echo 'export PATH="$HOME/project/venv/bin:$PATH"' >> $BASH_ENV
  - &ci-env
    environment:
      DJANGO_SETTINGS_MODULE: settings.ci

jobs:
  build-node:
      <<: *ci-env
      docker:
        - *docker-image
      steps:
        - checkout
        - *restore-cache
        - run:
            name: Install Node requirements
            command: |
              yarn --version
              yarn install --frozen-lockfile
        - save_cache:
            key: *cache-key
            paths:
              - node_modules
        - run:
            name: Build Javascript files
            command: yarn build
        - persist_to_workspace:
            root: .
            paths:
              - calchart/static/
  build-python:
      <<: *ci-env
      docker:
        - *docker-image
      steps:
        - checkout
        - run:
            name: Create virtual environment
            command: python -m venv venv
        - *activate-venv
        - run:
            name: Install Python requirements
            command: |
              pip --version
              pip install -r requirements/dev.txt
        - persist_to_workspace:
            root: .
            paths:
              - venv
  test-node:
      <<: *ci-env
      docker:
        - *docker-image
      steps:
        - checkout
        - *restore-cache
        - attach_workspace:
            at: .
        - run:
            name: Lint Javascript files
            command: |
              yarn list | grep eslint
              yarn lint
        - run:
            name: Run Javascript unit tests
            command: yarn test
  test-python:
      <<: *ci-env
      docker:
        - *docker-image
        - *postgres-image
      steps:
        - checkout
        - *restore-cache
        - attach_workspace:
            at: .
        - *activate-venv
        - run:
            name: Lint Python files
            command: |
              flake8 --version
              flake8 calchart/
        - run:
            name: Wait for PostgreSQL
            command: sleep 10
        - run:
            name: Run Django tests
            command: python manage.py test --verbosity 3 --noinput
            working_directory: calchart
  test-cypress:
      <<: *ci-env
      docker:
        - *docker-image
        - *postgres-image
      steps:
        - checkout
        - *restore-cache
        - attach_workspace:
            at: .
        - *activate-venv
        - run:
            name: Wait for PostgreSQL
            command: sleep 10
        - run:
            name: Run cypress tests
            command: yarn cypress:run
        - store_artifacts:
            path: cypress/videos
        - store_artifacts:
            path: cypress/logs

workflows:
  version: 2

  calchart:
    jobs:
      - build-node
      - build-python
      - test-node:
          requires:
            - build-node
      - test-python:
          requires:
            - build-python
      - test-cypress:
          requires:
            - build-node
            - build-python
